### ISSUE TITLE
It looks like something is not working correctly in the module

### ISSUE THREAD

**Issue by Limych** [MatthewFlamm/pytest-homeassistant-custom-component#106]
Situation: at the testing stage, error "homeassistant.loader.IntegrationNotFound: Integration 'jq300' not found." began to pop up steadily. The testing code did not change, and there was no such error before. When tested on real HA, everything works correctly.

https://github.com/Limych/ha-jq300/runs/4725979918?check_suite_focus=true

UPD. At the same time, for some reason, other projects do not have this problem. Perhaps the reason is in the name of the project.

**Comment by MatthewFlamm** [comment]
Are you using `enable_custom_integrations` fixture?

**Comment by MatthewFlamm** [comment]
I don't see it in a quick look through your testing code:

https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/blob/master/tests/conftest.py

**Comment by MatthewFlamm** [comment]
https://github.com/Limych/ha-jq300/pull/80 fixes the testing, I will close this.

**Comment by Limych** [comment]
Thanks for taking a fresh look at my code. Sometimes, as you can see, I also make stupid mistakes :)
