### ISSUE TITLE
Move to newer version of pytest-aiohttp

### ISSUE THREAD

**Issue by masaccio** [MatthewFlamm/pytest-homeassistant-custom-component#128]
The package is fixed at pytest-aiohttp==0.3.0 which is [almost 5 years old](https://pypi.org/project/pytest-aiohttp/0.3.0/) and given  the dependency, poetry refuses to add newer versions of pytest-aiohttp.

So adding the caveat that new to asyncio and HA and trying to migrate an existing API to asyncio to create a custom integration, I do seem to be in a Python dependency hole. If I try and make use of pytest-aiohttp 0.3.0 I don't get anywhere useful due to:

`pytest_socket.SocketBlockedError: A test tried to use socket.socket.`

Short of forking your package and trying to move it to a newer pytest-aiohttp, any ideas?

**Comment by MatthewFlamm** [comment]
This package is 99.5% direct from homeassistant repo.  The dependencies are included in that portion.  See https://github.com/home-assistant/core/blob/157222126ea25819fc34370c00e993ca77b18073/requirements_test.txt#L19.  This package's goal is to be as faithful to the homeassistant testing environment as possible.

See #96 for socket related information.

**Comment by masaccio** [comment]
Ah that's a much bigger codebase to chew on such a change then. Given the strict dependencies on HA I'll probably create a separate package for the HA integration of my API and then I have more freedom with package versions for the API testing itself. I'll close this -- thanks for the quick follow-up.

**Comment by MatthewFlamm** [comment]
> Given the strict dependencies on HA I'll probably create a separate package for the HA integration of my API and then I have more freedom with package versions for the API testing itself.

I think you have the right idea.  This is highly recommended.
