### ISSUE TITLE
Async issue

### ISSUE THREAD

**Issue by knudsvik** [MatthewFlamm/pytest-homeassistant-custom-component#129]
It may be just my incompetence here, but I cannot get these pytests to work for my (first) integration [EnergyScore](https://github.com/knudsvik/EnergyScore). I have written/copied a very basic test to get started with tests but when I run `pytest tests/` it keeps throwing me an async error.

```python
async def test_energyscore(hass):
    """Test EnergyScore config."""
    entry = MockConfigEntry(domain=DOMAIN, data=FAKE_CONFIG_DATA)
    entry.add_to_hass(hass)
    assert await hass.config_entries.async_setup(entry.entry_id)
    await hass.async_block_till_done()

    assert "energyscore" in hass.config.components
```

The error:
```
PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
  You need to install a suitable plugin for your async framework, for example:
    - anyio
    - pytest-asyncio
    - pytest-tornasync
    - pytest-trio
    - pytest-twisted
```

Every example I look at uses async definitions, so most likely I am missing something here. I tried `pip install pytest-asyncio` without any difference.

**Comment by MatthewFlamm** [comment]
It would be useful to see how you are installing your test environment including python version and package versions.  Also make sure that you are running your tests using the pytest executable you expect. You might need to do `python -m pytest tests/` if this is a problem or invoke a particular python executable, etc.

**Comment by MatthewFlamm** [comment]
This is weird, none of this is in the requirements for the homeassistant/core tests or the tests for this package.  See https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/blob/master/tests/test_sensor.py which looks very close to the test you shared.

**Comment by knudsvik** [comment]
> It would be useful to see how you are installing your test environment including python version and package versions. 

I created a pyenv environment based on Python 3.10.4 and ran `pip install pytest-homeassistant-custom-component`on it and then ran `pytest tests/` from the root directory of the custom component. 

> You might need to do `python -m pytest tests/` if this is a problem or invoke a particular python executable, etc.

Produced the same result...

**Comment by knudsvik** [comment]
> I had the same problem and solved it like this: https://github.com/henricm/ha-ferroamp/pull/253/files
> 
> It's probably just the `janus`-dependency and the `asyncio_mode` that is needed for you.

I tried installing Janus, but it was already satisfied. So looked at the setup.cfg file, mine did not have anything on pytest, so I copied what you had in your file and voila! It works! :) I haven't changed that file from forking the [integration blueprint](https://github.com/custom-components/integration_blueprint) so I guess I should make a PR to that repo (but seems like it's not being updated anymore).

**Comment by argoyle** [comment]
Cool, happy to have helped.

**Comment by MatthewFlamm** [comment]
After looking into this, I'm baffled by why the tests for this package pass without setting `auto_mode=True`.  The default is strict mode https://pytest-asyncio.readthedocs.io/en/latest/concepts.html#strict-mode.  home-assistant/core does this as well.

**Comment by mvdwetering** [comment]
FYI I also ran into this after upgrading pytest-homeassistant-custom-component from 0.12.9 to 0.12.34 for my custom component (https://github.com/mvdwetering/yamaha_ynca)

Marking tests with `@pytest.mark.asyncio` or running with `pytest tests --asyncio-mode=auto` makes the error go away. Creating a `setup.cfg` like in the linked PR did not work for me.

I ended up extending the existing `[tool.pytest.ini_options]` section in my `pyproject.toml` with the `asyncio_mode = "auto"` option. Which solved it for me.

**Comment by graham33** [comment]
I ran into this, I think the change in behaviour comes from upgrading pytest-asyncio, which has removed the default legacy behaviour and now requires `asyncio_mode` to be set to strict or auto (https://github.com/pytest-dev/pytest-asyncio/blob/master/CHANGELOG.rst#0200-22-10-21). Setting it to auto fixed things for me.
