### ISSUE TITLE
custom_components again

### ISSUE THREAD

**Issue by krahabb** [MatthewFlamm/pytest-homeassistant-custom-component#137]
I see there some other similar issues already fixed/closed (#106 or #64) about this but there's something apparently more subtle here or I'm not getting it right (it could be since I'm still far from grasping all of these frameworks and python itself)

If I got it right these issues could be not related to the fixture or so but to the fact the installation of pytest-homeassistant-custom-component creates a custom_components directory into the site-packages of the python environment and this in turn messes up the HA core loader.

This is my setup:
I'm using a forked custom_integration [blueprint](https://github.com/custom-components/integration_blueprint) repository to setup my dev environment and everything works fine (or looks like).
When I invoke the `pip install -r requirements_test.py` from the root workspace folder inside my devcontainer it nicely installs everything (I'm actually on version `pytest_homeassistant_custom_component-0.12.54`) but also creates the custom_components (sample?) folder inside the site-packages of the environment.
When HA starts the loader tries to import the custom_components root module and it obviously find it into the site-packages (I've opened an issue on HA core thinking this is wrong but they rejected this as non pertinent to the core) but that folder is far from being the one on which us, custom integration developers, are working.

Maybe I'm doing it wrong by invoking the pip install inside the container or I'm in the wrong place anyway but this is subtle and took half a day to be able to debug the HA loading process in these early stages.

The behavior was: when HA starts it doesnt find my custom integration since it is looking in a completely wrong folder (or at least a folder where no-one expects to put custom_components)

I still think this is a relatively bad behavior for the HA core and should be fixed but also I don't get why the pip install should put sample folder data inside the site-packages

**Comment by MatthewFlamm** [comment]
Not quite following everything here, but you rightly point out that this package is mistakenly adding a `custom_components` package, which shoudl only be used for internal testing.  We should move to a src-layout to avoid this.

**Comment by krahabb** [comment]
Yep sorry I get quite verbose..but my suspect too was the custom_components folder shouldnt get there.
At any rate, this behavior is very subtle: I'm working on 2 different integrations with different instances of the same container image and 1 constantly refuses to load the correct 'custom_components' while the other works flawlessly (both have the rogue 'custom_components' folder in the site-packages)
