### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by bruxy70** [MatthewFlamm/pytest-homeassistant-custom-component#142]
Home Assistant 2023.2.0 supports Python 3.11. So I tried to test my custom components in Python 3.11.2.
Created new venv, installed homeassistant 2023.3.0b7, pytest-homeassistant-custom-component 0.13.3.
Running pytest throws an error:
```
File "/Users/vasek/GitHub/Holidays/venv11/lib/python3.11/site-packages/pytest_homeassistant_custom_component/plugins.py", line 116, in <module>
from .asyncio_legacy import legacy_coroutine
ModuleNotFoundError: No module named 'pytest_homeassistant_custom_component.asyncio_legacy'
```
I have verified that pytest_homeassistant_custom_component really does not contain asyncio_legacy.

**Comment by MatthewFlamm** [comment]
I have 3/4 of a mind to just wait until this resolves itself, but there also should be no problem to fix it temporarily in the meantime.

https://github.com/home-assistant/core/pull/88560

**Comment by MatthewFlamm** [comment]
This package should now support Python 3.11 when the next release is made (next homeassistant release).
