### ISSUE TITLE
Async_test_home_assistant.<locals>.async_create_task() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by jmcollin78** [MatthewFlamm/pytest-homeassistant-custom-component#147]
Hello,

I try to update homeassistant with 2023.3.1 release and it breaks all my unit tests.
I try to update pytest-homeassistant-custom-component with 0.13.5 and the failure is still there.

The failure is:
```

hass = <homeassistant.core.HomeAssistant object at 0xffff896da950>
domain = 'versatile_thermostat'
config = {'_': 'Not empty or else some bad checks for hass config in discovery.py breaks'}

    async def async_setup_component(
        hass: core.HomeAssistant, domain: str, config: ConfigType
    ) -> bool:
        """Set up a component and all its dependencies.
    
        This method is a coroutine.
        """
        if domain in hass.config.components:
            return True
    
        setup_tasks: dict[str, asyncio.Task[bool]] = hass.data.setdefault(DATA_SETUP, {})
    
        if domain in setup_tasks:
            return await setup_tasks[domain]
    
>       task = setup_tasks[domain] = hass.async_create_task(
            _async_setup_component(hass, domain, config), f"setup component {domain}"
        )
E       TypeError: async_test_home_assistant.<locals>.async_create_task() takes 1 positional argument but 2 were given

```

I try to rollback but didn't succeed yet to find two compatible releases:

```
vscode ➜ /workspaces/core (dev) $ pip list|grep homeassistant 
atomicwrites-homeassistant            1.4.1
homeassistant                         2023.3.1
pytest-homeassistant-custom-component 0.13.5
```

**Comment by jmcollin78** [comment]
Ok I finally found that those releases should be compatible but my dev env was in the homeassistant package was in "dev" branch and this is not more compatible. I will close the issue.

**Comment by MatthewFlamm** [comment]
Yes #59 could be used in the future if you want to test against dev branch.  In fact, the rudimentary start of this exists.  But, for now you have to clone this repo to use it.  It will take multiple steps on a CI workflow to get it to work.

Another problem is that this package is brittle to upstream homeassistant changes.  The approach of testing against bleeding edge dev will often fail for this reason.
