### ISSUE TITLE
Error by simply loading the plugin: A test tried to use socket.socket

### ISSUE THREAD

**Issue by fredck** [MatthewFlamm/pytest-homeassistant-custom-component#171]
I am encountering an error when attempting to run pytest with the `homeassistant-custom-component` plugin. The tests fail to run, and the "A test tried to use socket.socket" error is thrown.

**Environment:**
- Operating System: MacOS
- Development Environment: Visual Studio Code in a dev container (python:3.11-bullseye)
- Python Version: 3.11.6
- Pytest Version: 7.4.3

**Steps to Reproduce:**
1. Set up a Python development environment in a VS Code dev container (python:3.11-bullseye).
2. Install pytest and the `homeassistant-custom-component` plugin.
3. Write a basic test case:
   ```python
   def test_init():
       assert True
   ```
4. Run pytest.

**Expected Behavior:**
The test suite runs without any issues.

**Actual Behavior:**
The test suite fails to start, and the following error is displayed:

```
CLIENT: Server listening on port 34081...
Received JSON data in run script
============================= test session starts ==============================
[...]
tests/components/lightener/test_init.py Error attempting to connect to extension communication socket[vscode-pytest]: A test tried to use socket.socket.
If you are on a Windows machine, this error may be occurring if any of your tests clear environment variables as they are required to communicate with the extension. Please reference https://docs.pytest.org/en/stable/how-to/monkeypatch.html#monkeypatching-environment-variables for the correct way to clear environment variables during testing.
```

**Additional Information:**
- This issue occurs before any of the tests have a chance to run.
- The environment is set up on a Mac computer running in a Linux dev container. No Windows involved.

Any guidance or suggestions to resolve this issue would be greatly appreciated. Thank you.

**Comment by fredck** [comment]
To make it easy to confirm the issue, I've created this minimal VSCode project: [socket-error.zip](https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/files/13401824/socket-error.zip)

Just open this in VSCode:

 - When asked, open it in a dev container (this ensures isolation from any other python depedency)
 - After loading, open the a VSCode terminal in the dev container and execute: `pip install --requirement requirements.txt`
 - Go to the Testing tab in VSCode. Run the tests.
   - The "A test tried to use socket.socket" error will be thrown and no test run will happen.

**Comment by fredck** [comment]
* This issue happens only (and always) when running tests using the VSCode Testing tab
 * It doesn't happen if the plugin is unistalled
 * It doesn't happen if running `pytest` from the command line in the dev container, even with the plugin installed

The conclusion is that the plugin is breaking the VSCode testing infrastructure somehow.

**Comment by fredck** [comment]
For those wasting their lives with this issue, I was able to fix it by adding the following configuration to the VSCode settings:

```
"python.experiments.enabled": false
```

For reference:
https://github.com/microsoft/vscode-python/wiki/AB-Experiments

**Comment by PeteRager** [comment]
i continue to waste my time with this issue.  I've added that setting, tried many different things and its still broke.  The only thing that seems to work is commenting out the code in this modules plugin.py

```
#    pytest_socket.socket_allow_hosts(["127.0.0.1"])
#    pytest_socket.disable_socket(allow_unix_socket=True)
```
