### ISSUE TITLE
Latest releases not on PyPi

### ISSUE THREAD

**Issue by mvdwetering** [MatthewFlamm/pytest-homeassistant-custom-component#175]
_You might already be aware as I see quite some action the last few days, but just to be sure._

The last 2 releases for HA 2024.1.0b8 and 2024.1.0 are released on Github, but are not visible on PyPi.

Twine errors out with the following message in CI
https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/actions/runs/7402237250/job/20139743707#step:13:201
```
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         Username/Password authentication is no longer supported. Migrate to API
         Tokens or Trusted Publishers instead. See                              
         https://pypi.org/help/#apitoken and                                    
         https://pypi.org/help/#trusted-publishers                              
Error: Process completed with exit code 1.
```

It seems like it is just a case of either updating TWINE_USERNAME / TWINE_PASSWORD secrets with "__token__" and a new token. Or setting up a Trusted Publisher, which seems fancier, but also more complicated. The links in the error message have all the info.

**Comment by MatthewFlamm** [comment]
Yes, the pypi upload should hopefully be fixed but now there are new errors since the testing has changed in the newest patch releases

**Comment by MatthewFlamm** [comment]
Latest release now on pypi.
