### ISSUE TITLE
Automatic releases are failing (for 2024.4 beta)

### ISSUE THREAD

**Issue by danieldotnl** [MatthewFlamm/pytest-homeassistant-custom-component#192]
There are no new releases being build for the 2024.4 beta releases. Probably due to an error with this action: https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/actions/runs/8517656033

Tomorrow the 2024.4 release is coming out and I really hope I can test my custom components against it!

Thank you!

**Comment by MatthewFlamm** [comment]
Fixed in #193 and released in https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/releases/tag/0.13.110

**Comment by danieldotnl** [comment]
It's happening again? No releases are created for 2024.8.x

**Comment by MatthewFlamm** [comment]
Fixed in https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/releases/tag/0.13.149

**Comment by danieldotnl** [comment]
Thank you Matthew!!
