### ISSUE TITLE
local import fails in >= 0.0.16 but worked in 0.0.8

### ISSUE THREAD

**Issue by craigbarratt** [MatthewFlamm/pytest-homeassistant-custom-component#23]
First, thanks for `pytest-homeassistant-custom-component`, which I adopted a couple of months ago for pyscript, which has quite a few tests.

I am currently using 0.0.8, and everything worked fine.  I just tried 0.0.20, but for reasons I don't understand my test files are unable to import from `custom_components.pyscript`.  For example, if I run this from the top-level a clone of the pyscript directory:
```
pytest tests/test_unit_eval.py
```
I get the error:
```
ImportError while importing test module '/Users/craig/git/pyscript/tests/test_unit_eval.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_unit_eval.py:3: in <module>
    from custom_components.pyscript.const import CONF_ALLOW_ALL_IMPORTS, CONFIG_ENTRY, DOMAIN
E   ModuleNotFoundError: No module named 'custom_components.pyscript'
```
I'm doing something wrong, but can't readily figure it out.

I'm running python 3.8.3 with:
```
homeassistant-custom-component==0.0.20
pytest==6.1.2
homeassistant==0.118.2
```
I created a clean `venv` and got the same issue.

I also tried cloning `pytest-homeassistant-custom-component` with its own `venv`, and after installing its dependencies, I used that `venv` and it does succeed in the import, although it gets a different error:
```
E       fixture 'hass' not found
>       available fixtures: aiohttp_client, aiohttp_raw_server, aiohttp_server, aiohttp_unused_port, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, fast, loop, loop_debug, monkeypatch, no_cover, proactor_loop, pytestconfig, raw_test_server, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, test_client, test_server, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_port, worker_id
>       use 'pytest --fixtures [testpath]' for help on them.
```
But after I install `pytest-homeassistant-custom-component==0.0.20` in that 2nd working `venv`, the import fails.

Do you have some ideas I can try?

**Comment by MatthewFlamm** [comment]
Have you tried adding a `custom_components/__init__.py`?

I haven't fully wrapped my head around pytest and why things get weird in this case, but see https://stackoverflow.com/questions/50174130/how-do-i-pytest-a-project-using-pep-420-namespace-packages

Im not sure why it would work in one version and boy the next though.

**Comment by craigbarratt** [comment]
That did it!  Wow, thanks!

**Comment by MatthewFlamm** [comment]
I originally had this disclaimer in the README but then somehow convinced myself that it was unneeded by testing it (probably in a version around 0.0.8).  The other question is how home assistant is able to get around this, I haven't figured that out yet either :)

**Comment by MatthewFlamm** [comment]
It sounds like this is fixed.  I will close, but feel free to reopen if there are still problems
