### ISSUE TITLE
load_fixture looking for fixtures file within site-packages/pytest_homeassistant_custom_component/fixtures

### ISSUE THREAD

**Issue by ehendrix23** [MatthewFlamm/pytest-homeassistant-custom-component#41]
I import load_fixture from  pytest_homeassistant_custom_component.common:

`from pytest_homeassistant_custom_component.common import MockConfigEntry, load_fixture`

I then try to use it with following code:
`devices_fixture = "devices.json"`
`devices_json = load_fixture(devices_fixture)`

I created a fixtures folder within my tests folder in which I put devices.json file.

When running the test using pytest I get the error that the file is not found. 
For filename it was trying to load it shows: 
`venv/lib/python3.8/site-packages/pytest_homeassistant_custom_component/fixtures/devices.json`

Looking at the code it does:
`path = os.path.join(os.path.dirname(__file__), "fixtures", filename)`

For HASS, the method is located in tests.common; thus dirname would be tests and thus with the join it would be tests\fixtures\filename. 
But here the method ends up being located in venv/lib/python3.8/site-packages/pytest_homeassistant_custom_component instead.

**Comment by MatthewFlamm** [comment]
Thanks for the report and the detailed information. 
Thiss is indeed an issue caused on the separate nature of the testing helpers and the tests themselves.

**Comment by MatthewFlamm** [comment]
In addition to `load_fixture`, the following locations also use `__file__` and likely won't work as intended:

* `load_fixture`
* `get_test_config_dir`
* `MockModule`
*  `MockPlatform`

The first is definitely usable in custom component testing.  I doubt the last two would be used in custom components and I'm not sure about the second.

**Comment by ehendrix23** [comment]
I did find a way how to get path of current test script being executed, but I could not get it to work. My knowledge on this part of limited and clearly being doing something wrong.

It is using py test fixture and request.fspath. See:https://stackoverflow.com/questions/34504757/get-pytest-to-look-within-the-base-directory-of-the-testing-script

Not sure if it might even just be a matter in leveraging that to then allow all 4 easily to be fixed? Otherwise I would say that load_fixture probably is the most used one of the 4. :-)

**Comment by MatthewFlamm** [comment]
I think there are two straightforward ways to proceed here. I'm leaning towards the second option, but I need to think about what is the best implementation.

1. You can place your own `load_fixture` function (just copy it directly from `common.py` into a `common.py` module (or whatever you want) inside your `tests` directory.  Then, you can put your file inside `tests/fixtures/`, since the new `load_fixture` function is inside of your `tests` folder.  I think this should work.
2. This library could either override the default `load_fixture` function or provide a new function to provide a way to pass in the absolute path of the testing function.  So instead of doing `load_fixture("file.json")` you would do `load_fixture("file.json", __file__)`.  Then, since `__file__` is provided from the test module itself, we get the correct path.

**Comment by MatthewFlamm** [comment]
> It is using py test fixture and request.fspath.

I'm not quite sure about this, but since `load_fixture` is just a function, not a fixture, that is imported, I don't think we can use `request` fixture to fix this.  I think it still requires changing `load_fixture` itself.

**Comment by ehendrix23** [comment]
Personally I like option 2 then. :-)

**Comment by MatthewFlamm** [comment]
I've thought of a third option, and it is more elegant and preserve the current usage.  `traceback.extract_stack` might be able to extract the path to the test module or other module that calls `load_fixture`.  Then it is a like for like usage with the built-in tests, which is a goal of this library.

**Comment by MatthewFlamm** [comment]
@ehendrix23 

Are you able to test #42 ?

**Comment by ehendrix23** [comment]
> @ehendrix23
> 
> Are you able to test #42 ?

Patched based on the changes and then  ran the test and it worked beautifully. 
Using load_fixture just as one normally would. Folder fixtures is located in folder tests and my test scripts are also located within folder tests.

Only thing I could potentially see with this is if one has a structure like:
```
   tests/
      fixtures/  
          fixture.json
      component/    
           test.py
```

In that case it would look for folder fixtures in component whereas HASS looks in tests/fixtures.
Now I don't think too many folks would have this as most would just have their tests within tests. And if they do then they just need to  put fixtures within component folder instead. :-)

Maybe that is just a restriction then. :-)

But works for me. Thx!!!!

**Comment by MatthewFlamm** [comment]
Great thanks!  I am just testing the automatic extraction to produce these changes, and then I will push a new version.

> And if they do then they just need to put fixtures within component folder instead.

You are correct, the fixture folder needs to be colocated with the tests that use them. I think the only way to avoid this is to walk through the directory structure somehow.  That opens a rabbit hole that I'm not willing to go down 😄

**Comment by ehendrix23** [comment]
Let me know when available and I'll update mine and retest again making sure we're all good. :-)

**Comment by MatthewFlamm** [comment]
You can try v0.20. and if it doesn't work, please reopen here.

**Comment by ehendrix23** [comment]
Works! Thx!
