### ISSUE TITLE
Odd error while testing locally

### ISSUE THREAD

**Issue by firstof9** [MatthewFlamm/pytest-homeassistant-custom-component#46]
While attempting to run tests locally in my Home Assistant venv build from the dev branch I get the following errors when testing custom components:

```log
ERROR    homeassistant:runner.py:93 Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/mnt/g/github/core/homeassistant/helpers/entity_platform.py", line 301, in async_add_entities
    device_registry = await hass.helpers.device_registry.async_get_registry()
  File "/mnt/g/github/core/homeassistant/helpers/device_registry.py", line 632, in async_get_registry
    return async_get(hass)
  File "/mnt/g/github/core/homeassistant/helpers/device_registry.py", line 616, in async_get
    return cast(DeviceRegistry, hass.data[DATA_REGISTRY])
KeyError: 'device_registry'
```
```log
../core/venv/lib/python3.8/site-packages/pytest_homeassistant_custom_component/plugins.py:147:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../core/homeassistant/helpers/entity_platform.py:301: in async_add_entities
    device_registry = await hass.helpers.device_registry.async_get_registry()
../core/homeassistant/helpers/device_registry.py:632: in async_get_registry
    return async_get(hass)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

hass = <homeassistant.core.HomeAssistant object at 0x7f66a99fe460>

    @callback
    def async_get(hass: HomeAssistantType) -> DeviceRegistry:
        """Get device registry."""
>       return cast(DeviceRegistry, hass.data[DATA_REGISTRY])
E       KeyError: 'device_registry'

../core/homeassistant/helpers/device_registry.py:616: KeyError
```

I've rebuilt the venv multiple times with no success in resolving this error.

Do you have any advice?

**Comment by MatthewFlamm** [comment]
I _think_ this is due to the fact that this package currently has no way to link homeassistant versions to the testing version. This also caused the latest automatic extraction here to fail in #45.

Right now, it pulls the latest homeassistant version available on PyPI when installing, but it extracts the latest dev branch from homeassistant/core.

One possible workaround is to pin both homeassistant version (install this first) and the version here.  Addressing #43 should fix most of these issues, but I haven't decided on what the best way to implement is yet.

**Comment by MatthewFlamm** [comment]
Can you check what combinations of homeassistant and pytest-homeassistant-custom-component you are using?

**Comment by firstof9** [comment]
pip3 freeze is giving me this:
```
home-assistant-frontend==20210208.0
-e git+https://github.com/firstof9/core.git@f045c0512b063569a18d7d40fa7c36ac757b3beb#egg=homeassistant
homeassistant-pyozw==0.1.10
...
pytest==6.1.2
pytest-aiohttp==0.3.0
pytest-cov==2.10.1
pytest-forked==1.3.0
pytest-homeassistant-custom-component==0.1.0
pytest-runner==5.3.0
pytest-sugar==0.9.4
pytest-test-groups==1.0.3
pytest-timeout==1.4.2
pytest-xdist==2.1.0
```

**Comment by MatthewFlamm** [comment]
This indicates you are running on homeassistant dev or close to it?  Then this will definitely be the same issue as #45 ran into.  I'm not sure that we can support running arbitrary bleeding edge dev versions unless it is updated daily or something like that.

`git+https://github.com/firstof9/core.git@f045c0512b063569a18d7d40fa7c36ac757b3beb#egg=homeassistant`

**Comment by firstof9** [comment]
Ya I rebase it off dev while submitting PRs and the like, I was just mostly making sure I wasn't crazy and that something weird just happen to be occurring.

**Comment by MatthewFlamm** [comment]
Actually, with #43 addressed, you could still do this.  You'd have to generate your own version of this package using the automatic extraction from the same commit as your local homeassistant repo.  I'm not sure how critical it is to support extraction from a local repo rather than from homeassistant/core

**Comment by firstof9** [comment]
If I pip install homeassistant into the venv it should basically start working correctly again right?

**Comment by MatthewFlamm** [comment]
It should, but there were recently a few changes in homeassistant/core that require the versions to be closely in sync.  You may have to downgrade homeassistant versions to match your pinned pytest-homeassistant-custom-component version.

**Comment by firstof9** [comment]
Yup looks like dropping homeassistant back to 2021.2.3 in the venv resolved the issue.

Thank you for your time once again @MatthewFlamm

**Comment by MatthewFlamm** [comment]
@firstof9 With the new release of homeassistant, I updated here.  You should now be able to upgrade this library and homeassistant version.   I'm still kicking around in my head what the best method is to pin versions of homeassistant to this library.

**Comment by firstof9** [comment]
The updated release does indeed work.
