### ISSUE TITLE
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_load'

### ISSUE THREAD

**Issue by Limych** [MatthewFlamm/pytest-homeassistant-custom-component#47]
There was a very strange error while writing tests. I can't understand if I messed up something, or a bug in your module.

```
            await asyncio.gather(
>               device_registry.async_load(hass),
                entity_registry.async_load(hass),
                area_registry.async_load(hass),
            )
E           AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_load'

../../.local/lib/python3.8/site-packages/pytest_homeassistant_custom_component/common.py:288: AttributeError
```

Python 3.8
homeassistant==2021.2.3
pytest-homeassistant-custom-component==0.2.1

**Comment by MatthewFlamm** [comment]
This is because #43 hasn't been addressed yet.  It is caused by mismatch in version between homeassistant published to PyPI and the version used to generate this package.

You either need to upgrade homeassistant version to latest or downgrade pytest-homeassistant-custom-component version to 0.2.0

**Comment by Limych** [comment]
Thank you.

I guess then it makes sense in the settings of pytest-homeassistant-custom-component to clearly prescribe the version of homeassistant with which it works. So pip will automatically pull up dependencies correctly.

**Comment by MatthewFlamm** [comment]
It is currently tricky since everything is automatic and pulls from the dev branch.  There are no matching versions on PyPI.

The options are to specify installing homeassistant directly from GitHub, which needs more testing, or creating the package here from a release branch like rc or master using tags.

**Comment by Limych** [comment]
When generating a package, the current version of Home Assistant is determined. Why not just create a `requirements.txt` file with text like `homeassistant~={__version__}` ?

**Comment by MatthewFlamm** [comment]
This version is `2021.4.0.dev0` since it is based on dev branch of core.  This version does not exist on PyPI.

**Comment by Limych** [comment]
Yes, I can see it.
But then there is a risk that the automatically generated package may not work on the stable version.
When generating `requirements.txt`, you can trim the version a little. Write three numbers instead of four. Then `homeassistant~=2021.4.0` will be specified, which will actually equal the rule `homeassistant>=2021.4.0,<2021.5.0`.

And you can generate packages for two branches: for the stable one, take the code from the stable Home Assistant branch, for development — from the branch where the code is now taken from.
When `requirements.txt` are auto-generated, dependencies will also be generated correctly.

**Comment by MatthewFlamm** [comment]
This is a current pain point.  I'd like to settle on the best path forward before implementing.  I'm not sure yet.

Note that `2021.4.0` is also not an available version currently.  Since it is generated from the `HEAD` of the `dev` branch.  It is possible to install homeassistant directly from github using a commit ref, so it is possible to pin it this way.  The big advantage here is being able to test your custom component with the most up to date version possible.

The other option is to instead extract from the `rc` or `master` branch which would have the latest releases available on PyPI.  Distinguishing which is the most recent between the branches is a hurdle here, but probably doable.  Another downside is that I then need to synchronize updates with homeassistant, which is too much work for me.  The big advantage here is you could image setting up a battery of tests in CI to test your component against versions X-Y of homeassistant.

I'm leaning towards simply using the commit ref from dev branch as this is the most straightforward to implement.  I'm not sure how useful being able to test backwards to a very specific version is.  You would still be able to test backwards using dev branch commits, it just isn't as precise.

**Comment by Limych** [comment]
For me, the main problem is that I cannot predict in advance the compatibility of these two packages. For me, it would be enough if the dependency was specified in the option "not lower than this version".

The fact is that I have a master repository with a common component template. This is where the dev dependencies are updated. And there is no way to check the full compatibility.
After this updates go to working repositories... Where do these strange errors "it is not clear why" come out.

**Comment by Limych** [comment]
Why not specify the dependency according to the principle "not lower than the latest stable version"?

Perhaps this will solve the problem ...

**Comment by MatthewFlamm** [comment]
This is indeed a major pain point.  Doing it this way, or pinning the way you suggest, limits the ability to test custom components against significant changes in home-assistant until there is a latest stable version.  I'd rather put in a better more permanent solution.

**Comment by Limych** [comment]
Not necessary.
Nobody bothers to establish that there are no restrictions at all for the dev version. And set restrictions only for stable versions.

**Comment by MatthewFlamm** [comment]
For a major breaking change codewise in homeassistant, it is critical. Otherwise, you would have to wait for the stable release to test it.  Many users would upgrade and your component might be broken.  I would consider using the latest beta version though.

**Comment by Limych** [comment]
No, it will not be critical if you set the restriction on the principle of "not less than this version."
But the limitation is needed. Just so that when the your package is updated, the Home Assistant core package would also be automatically updated.

**Comment by MatthewFlamm** [comment]
I think you are coming from the standpoint of this very particular issue here.  On a higher level, we should also support being able to test for upcoming changes.  How can this be done if we only generate this package for full stable release versions?

**Comment by Limych** [comment]
Please read my posts above more carefully: I have never suggested generating a package only for stable versions. But deliberately leaving ambiguity for an already stable version is bad.
The solution that I proposed last, in short: for stable (and / or beta) versions, hard link to the minimum (!) version of Home Assistant. For the dev version, leave everything as it is, or bind to a version no lower than the last stable one (of your choice).

In addition, it looks extremely strange that the STABLE (by number) version of your package works with the DEV version of Home Assistant. It would then be logical to make a direct association — stable with stable, dev with dev...
This discrepancy is also very confusing...

**Comment by MatthewFlamm** [comment]
> hard link to the minimum (!) version of Home Assistant.

This would also fail in the case you were using v0.2.0 (or any prior version) of `pytest-homeassistant-custom-component` after the newest home assistant release and before I generated a new version here.  This time, I was able to do it quickly, but there is no guarantee, I will always be able to.  We really need to pin to specific versions or commits, which I agree with you on that leaving it ambiguous is bad.

This package is generated directly from the git repo of homeassistant.  As such, there is no direct connection with PyPI releases.  The easiest method, obviously not the best, was to generate from the dev branch.  Relying on tags to represent PyPI releases might also bring challenges.  What if homeassistant forgets to tag a release in git?

Another friction is that I am not a homeassistant dev.  I cannot synchronize publishing this package with a homeassistant package to PyPI.  It is all automated through GitHub actions running at some interval.  In fact, it is explicitly the goal is this package to be as automatic as possible.

If you have suggestions on a method that enables this package to pin to specific versions that is automatic, please do so.  I am collecting my thoughts so far in #43 .

**Comment by Limych** [comment]
Yes, I, in fact, have already suggested. Perhaps it didn't look very obvious...

The logic is simple: version 0.2.0 worked fine until the latest stable release. To my question, you yourself said that a newer version of Home Assistant was used to generate version 0.2.1. And such failures will happen regularly. So, it doesn't make much sense to try to run a new build package on an old version of HA — you can use an old build package for that.

And the treatment is extremely simple:
- We take the HA version number, on the basis of which the package is generated.
- If HA version is stable, depending on we write `homeassistant~=<version number>`
- If it's a dev-version, write `homeassistant>=<last stable version number>`

As a result, we have one dev-version of package for the dev-version of HA and a history of stable builds of the package for different historical versions of HA.

The build system can also be automated according to the principle:
- All development is ALWAYS done only in the dev-version of package.
- The numbering of the dev-versions of package comes with the ".dev0" suffix in the version.
- If, while regularly trying to build a package, machine detects that a new version of HA has been released, it builds the stable version of the package instead. In this case, the suffix ".dev0" is removed from the version number, and after the generation of the package in the working branch, the patch number (the third part of version number) is automatically increased by 1. Then ".dev0" suffix is added back.

That's all.

**Comment by Limych** [comment]
As a basis for such an version auto-incrementing system, you can use a script to generate new releases from my common template for integrations: it just works on a very similar principle.
https://github.com/Limych/ha-blueprint/blob/master/bin/release

**Comment by MatthewFlamm** [comment]
There are several competing things here.  One is the ideal state, which I think you are getting close to "We should have a version of this package for every stable and beta release and possibly also the dev branch".  Another factor is complexity of the moving pieces between PyPI releases and git repos (which isn't a guarantee that they will be synced as it relies on home assistant updating tags and constants).  Previous releases from homeassistant have had issues with this on the dev version, which would have affected your workflow.  The final, and probably most important factor, is maintainability.  This is related to the second point as well.  Maintainability is one of the key criteria for how this package operates.  I am the sole maintainer/contributor (save for one documentation example, which I do appreciate greatly).  Having multiple branches to hold all the release types is not something I am interested in maintaining.

Given all of this, I am leaning farther and farther towards pinning this package to specific _commits_ in the home asisstant repo and require users to install from there.

**Comment by Limych** [comment]
What's the point of striving for perfect support for older versions? The Home Assistant system is developing not according to the principles of classic programs, but according to the principles of Continues Development. All stories about some bugs in previous versions will always have one answer: "Install the latest version." (By the way, exactly the same answer that you gave me at the very beginning of this communication :wink: )

Yes, it is sometimes useful to have a package history. But this is not an end in itself. It is more important to have a version that supports the latest HA code. Old versions of the package can be more useful only for cases when the developer has a slightly outdated version of HA installed in the process. And here it is just important that the package is not accidentally updated to a more recent build. Because then the tests will "break".

The algorithm I proposed above allows you to automatically set the boundaries of the package versions. I noticed that you already have a system for automatically suggesting edits to a new version. All that remains is to manually control so that these edits do not break the package code.

That's all...

**Comment by Limych** [comment]
By the way, following the principles of Continues Development, it makes sense to rename the package versions, synchronizing them with the HA versions. Anyway, the package code inseparably follows the HA code. Why then invent something? ..

For example, the major and minor versions of the package are taken from the HA version. At the same time, we still have a patch version that can be used to number any fixes inside the package code.

Or abandon our version numbering altogether, completely borrowing the number from HA ...

**Comment by MatthewFlamm** [comment]
We seem to be taking past each other, and this applies equally to my comments.

I 100% agree on pinning the homeassistant requirement in some form.  You have not been explicit in how we find the version we extract against.  We cannot intersperse stable release extractions with dev extractions due to good practice upstream of releasing dev branches.  This requires multiple branches as far as I understand.

I like the idea of taking the major.minor version here from HA directly and using patch as an internal signifier.  One idea is to number according to the _upcoming_ release using the dev branches and pin the homeassistant version to a specific commit. 

 That is, use dev branch head commit of homeassistant/core, to generate package.  While doing so, find __version__ and remove the patch and `.dev0`.  if that version already exists here, incrememt patch by 1.  As I understand, this is either what you propose or similar to it. Also, save the commit ref used to generate package.  Use commit ref to set installation in requirements.

Does this work for you?

**Comment by MatthewFlamm** [comment]
> What's the point of striving for perfect support for older versions? 

This is what I don't want to do.  I would rather have better support for current and upcoming versions, which is why I've based this solely on the `dev` branch of homeassistant/core so far.

**Comment by MatthewFlamm** [comment]
I think we are approaching this the wrong way currently.  We can make the entire homeassistant package available for testing inside this package from the same commit.
