### ISSUE TITLE
No support for hass.http

### ISSUE THREAD

**Issue by alandtse** [MatthewFlamm/pytest-homeassistant-custom-component#61]
I have a component that registers a http view with HA. This was originally intended as a core component but has migrated to a custom component. I have a set of tests that would setup that view and then use the aiohttp client to test the webserver. This worked with core.  While moving to a custom_component with this plugin, It looks like the hass fixture does not support this.

This is the example error from pytest in the [code](https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/homeassistant/components/tesla/config_flow.py#L119) being tested.

```console
>       self.hass.http.register_view(TeslaAuthorizationCallbackView())
E       AttributeError: 'NoneType' object has no attribute 'register_view'
```

Admittedly, implementing the http server may be outside the scope of this pytest plugin but I wanted to flag it for others who might run into this when they try to move tests from core into a custom_component.

**Comment by MatthewFlamm** [comment]
Thanks.  This is weird because this package is almost a literal repackaging of the home assistant testing package.

Can you provide the test that fails?

**Comment by MatthewFlamm** [comment]
Was this test implemented when part of the home assistant repo?  Did it pass then?

**Comment by MatthewFlamm** [comment]
If you are referring to this usage:

https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/tests/components/tesla/test_config_flow.py#L483

I don't see any use of this in tests except for the http integration itself, and I would note that the http integration is loaded before doing so, have you tried this?

**Comment by alandtse** [comment]
Thanks for looking into this. Yes, it is registering the view but it's in the implementation code. Not the test code. As part of the [start_oauth step](https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/homeassistant/components/tesla/config_flow.py#L80-L121), we register a callback view and a proxy view. See L119 and 120.

In the [failing test](https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/tests/components/tesla/test_config_flow.py#L95-L126), we are iterating through each step of the config flow with simulated user input (each test step calls the prior test):
```python
result = await hass.config_entries.flow.async_configure(
            flow_id,
            user_input={},
        )
```
When we enter the implementing code to set up the http view, it tries to access `self.hass.http` which is `None` at that point.

I am not mocking the integration setup phase at all and because the component has http as a [dependency](https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/homeassistant/components/tesla/manifest.json#L8), the http integration should be loaded by the very [first step](https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/tests/components/tesla/test_config_flow.py#L53-L55) of the config flow test.

As part of HA tests, this works as expected.

I did try to manually load the http component as a fixture, and still got the attribute error

```python
async def callback_view(hass, aiohttp_unused_port):
    """Generate registered callback_view fixture."""
    await async_setup_component(
        hass, http.DOMAIN, {http.DOMAIN: {http.CONF_SERVER_PORT: aiohttp_unused_port()}}
    )
    await async_setup_component(hass, DOMAIN, {})
    await hass.async_start()

    hass.http.register_view(TeslaAuthorizationCallbackView)
    return proxy_view
```

It's not in the posted code, but the relevant code is [here](https://github.com/alandtse/tesla/blob/dev/tests/test_config_flow.py#L493-L499).

**Comment by MatthewFlamm** [comment]
I wonder if it could be python dependency related.  If you are missing a Python dependency for http, will it fail to load?

**Comment by MatthewFlamm** [comment]
I think you are missing `aiohttp_cors`.  The following test works for me if this library is installed:

```python
async def test_http(hass, aiohttp_unused_port):
    await async_setup_component(
        hass, http.DOMAIN, {http.DOMAIN: {http.CONF_SERVER_PORT: aiohttp_unused_po
rt()}}
    )
    await hass.async_start()
    assert hass.http
```

I'm going to close this unless you have a minimal example that shows it doesn't work.

**Comment by alandtse** [comment]
I think that may have been it. I went ahead and added it for my test requirements. Should that be a dependency for this too?

**Comment by MatthewFlamm** [comment]
I think integrations using `http` are the exception, so I don't think it makes sense to include as a dependency.  You'll have to add to your requirements for your integration.  I don't know of a good way to get the same version that homeassistant uses, other than manually.

**Comment by MatthewFlamm** [comment]
One thought is to have `extras_require` to allow something like

```
pip install pytest-homeassistant-custom-component[http]
```

but then there might be a lot of possibilities to support.  Another option could be 

```
pip install pytest-homeassistant-custom-component[all]
```

where it would install everything from `requirements_test_all.txt`
