### ISSUE TITLE
Many strange errors when just upgrade library to v 0.4.0

### ISSUE THREAD

**Issue by Limych** [MatthewFlamm/pytest-homeassistant-custom-component#70]
There are brings many errors when I just upgrade library to v 0.4.0:

https://github.com/Limych/ha-blueprint/pull/35/checks?check_run_id=2708543813

```
hass = <homeassistant.core.HomeAssistant object at 0x7fbd477a49a0>
domain = 'integration_blueprint'

    async def support_entry_unload(hass: HomeAssistant, domain: str) -> bool:
        """Test if a domain supports entry unloading."""
        integration = await loader.async_get_integration(hass, domain)
>       component = integration.get_component()
E       AttributeError: 'Event' object has no attribute 'get_component'

/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/homeassistant/config_entries.py:1514: AttributeError
```
Src: https://github.com/Limych/ha-blueprint/pull/35/checks?check_run_id=2708543813#step:8:67

```
homeassistant.loader.IntegrationNotFound: Integration 'integration_blueprint' not found.
```
Src: https://github.com/Limych/ha-blueprint/pull/35/checks?check_run_id=2708543813#step:8:200
Note: At the same time, we can see earlier that the integration outputs data to the log — that is, it was initialized correctly.

etc...

**Comment by MatthewFlamm** [comment]
Have you tried using `enable_custom_integrations` fixture?  This is now required from homeassistant to load custom integrations in tests.

**Comment by MatthewFlamm** [comment]
If this works you could consider something like this: https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/blob/2b74f4d36caad86e9a7be9ccb18dfe92687e981c/tests/conftest.py#L5-L7

**Comment by Limych** [comment]
> Have you tried using `enable_custom_integrations` fixture? This is now required from homeassistant to load custom integrations in tests.

No, I've not tried this. Thanks.

Saw your commit to repository `custom-components/integration_blueprint`.
How nice, however, to have an automated update system!.. My repository [`Limych/ha-blueprint`](https://github.com/Limych/ha-blueprint) is linked directly to it via git (as it is a revised version of it). Now I will just merge your commits into my repository and the problem will be solved by itself. And then, in the same way, they will gradually creep into all my components - everything is connected there through the git. So now you will be a little the author of all my components.
Thank you very much! :)

**Comment by MatthewFlamm** [comment]
This seems to be addressed.
