### ISSUE TITLE
Tests fail on the new native_unit_of_measurement

### ISSUE THREAD

**Issue by Ernst79** [MatthewFlamm/pytest-homeassistant-custom-component#82]
Is it possible to release a version that uses HA 2021.9?
0.4.3 still uses 2021.8, causing failures of the pytests, as it doesn't know the new "native_unit_of_measurement"

**Comment by MatthewFlamm** [comment]
Forgot to make the release.  Try again

**Comment by Ernst79** [comment]
Thanks, it works.
