### ISSUE TITLE
How to test without config flow

### ISSUE THREAD

**Issue by parautenbach** [MatthewFlamm/pytest-homeassistant-custom-component#9]
I've written my first integration platform for HA I'm finding this testing framework very useful. 

I implemented my first version using a YAML config entry and thus haven't implemented a config flow. I will switch but thought I'd get my tests in place and then refactor the code. 

It seems like the framework relies on a config flow definition. Is there a way to tell the framework not to look for one?

Here's an extract from my code:
```python
async def test_async_media_play(hass, mqtt_mock):
    """Test that sending a play command from the player sends it via MQTT."""

    entry = MockConfigEntry(
        domain="media_player",
        data={
            "platform": "shairport_sync",
            "name": "Test",
            "topic": "expected/topic"
        },
    )

    entry.add_to_hass(hass)
    await hass.config_entries.async_setup(entry.entry_id)
    await hass.async_block_till_done()

    # more testing code and assertions
```

And the error:
```
INFO:homeassistant.setup:Setup of domain media_player took 0.0 seconds
ERROR:homeassistant.config_entries:Error importing platform config_flow from integration media_player to set up media_player configuration entry: No module named 'homeassistant.components.media_player.config_flow'
DEBUG:homeassistant.core:Bus:Handling <Event component_loaded[L]: component=media_player>
```

EDIT: Just a quick clarification: I didn't build a whole new media player integration: I only added another platform option for media players.

**Comment by MatthewFlamm** [comment]
I'm glad you are finding this useful!

This package simply copies all the testing frameworks from homeassistant core and makes them available to custom components.  You can setup a component and pass it a config like so:

```
result = await async_setup_component(hass, "media_player", config_data)
```

Try searching for async_setup_component in the homeassistant/core repository.

**Comment by parautenbach** [comment]
I was wondering whether I should try that route but that would mean I need to import modules from core (`from homeassistant.setup import async_setup_component`). Isn't the purpose of extracting the testing framework to avoid that dependency?

(I know I'm seeking help for something that I could probably be asking on the Discord channels too. I'm just worried that someone will give advice that requires my code to be part of the core repo, or the core devs might say pytest for homeassistant isn't their responsibility. Again, thankful for your help.)

**Comment by MatthewFlamm** [comment]
If you want to use a command from the testing framework, there is `assert_setup_component` too.  See [example](https://github.com/home-assistant/core/blob/9c1236b6de49a11e8c9d35c91b251c4b44183e5d/tests/components/ffmpeg/test_sensor.py#L26).  I see both being used in tests in the homeassistant repo.  

You will likely be importing constants from the homeassistant library itself for testing.  For example the media player domain can be imported.  The testing plugins and helpers also import from the base homeassistant library.  It is already required as a dependency.

> I know I'm seeking help for something that I could probably be asking on the Discord channels too.

This might be on topic there, but they might bristle on discussions of a third party testing library.  Maybe there should be a custom component developers discord channel.  But your issues seem to be more about how to write the test in general rather than on this specific library.

> The trouble is when I did something similar yesterday and tried what's in async def test_import(hass, mock_nwsradar) now, the hass.state object remains empty. I'm obviously missing something but I don't know what

I can't help without exactly what you did.

**Comment by parautenbach** [comment]
> If you want to use a command from the testing framework, there is assert_setup_component too. See example. I see both being used in tests in the homeassistant repo.

Thanks, I'm looking into this.

> You will likely be importing constants from the homeassistant library itself for testing. For example the media player domain can be imported. The testing plugins and helpers also import from the base homeassistant library. It is already required as a dependency.

Of course, I didn't think this through. 

> This might be on topic there, but they might bristle on discussions of a third party testing library. Maybe there should be a custom component developers discord channel. But your issues seem to be more about how to write the test in general rather than on this specific library.

I was thinking to phrase my question there as if I'm adding to HA core but I think I would've gotten myself in a twist if I then had to show code and it is non-HA core code. I'll ask whether there's support for a new channel. I do agree that my question here is perhaps more about testing in general – given my limited knowledge I wasn't sure. Feel free to point me away if I'm using your time inappropriately. 

> I can't help without exactly what you did.

I shouldn't expect anybody to read minds. :-) Here are all the tests I've written. `test_1` is at least logically what I'd like to test but then realised I'm doing something wrong setting up my entity. All the other tests just show the different ways I've tried to do this given all the examples I've looked at (here, HA core tests and other third-party components). I'm pretty sure they have a common problem – just no idea what.

```python
async def test_1(hass, mqtt_mock):
    random_name = "Random Name"
    expected_base_topic = "expected/topic"
    player = media_player.ShairportSyncMediaPlayer(
        hass, random_name, expected_base_topic
    )

    # fails
    # state = hass.states.get("media_player.test")
    # assert state is not None

    # from the class under testing:
    # async def async_media_play(self):
    #     """Send play command."""
    #     _LOGGER.debug("Sending play command")
    #     async_publish(self.hass, self._remote_topic, COMMAND_PLAY)
    await player.async_media_play()

    # alternative invocation seen in core tests
    # asyncio.run_coroutine_threadsafe(
    #     player.async_media_play_pause(), hass.loop
    # ).result()

    # fails
    assert mqtt_mock.async_publish.called


async def test_2(hass):
    config = {
        "platform": "shairport_sync",
        "name": "Test",
        "topic": "expected/topic"
    }
    result = await async_setup_component(hass, "media_player", config)
    await hass.async_block_till_done()
    assert result

    state = hass.states.get("media_player.test")
    # fails
    assert state is not None


async def test_3(hass):
    mock_async_add_entities = AsyncMock()
    config = {
        "platform": "shairport_sync",
        "name": "Test",
        "topic": "expected/topic"
    }
    # how do i get the player instance and if i can't, how can i call it's members?
    await media_player.async_setup_platform(hass, config, mock_async_add_entities)
    assert mock_async_add_entities.called

    state = hass.states.get("media_player.test")
    # fails
    assert state is not None


async def test_4(hass):
    entry = MockConfigEntry(
        domain="media_player",
        data={
            "platform": "shairport_sync",
            "name": "Test",
            "topic": "expected/topic"
        },
    )

    entry.add_to_hass(hass)
    # is this the right method to call?
    await hass.config_entries.async_setup(entry.entry_id)
    await hass.async_block_till_done()

    state = hass.states.get("media_player.test")
    # fails
    assert state is not None


# copied from nwsradar/test_no_loop
async def test_5(hass):
    """Test that nws setup with config yaml."""
    entry = MockConfigEntry(
        domain="media_player",
        data={
            "platform": "shairport_sync",
            "name": "Test",
            "topic": "expected/topic"
        },
    )
    entry.add_to_hass(hass)

    await hass.config_entries.async_setup(entry.entry_id)
    await hass.async_block_till_done()

    assert len(hass.states.async_entity_ids("media_player")) == 1
    assert (
        hass.states.async_entity_ids("media_player")[0]
        == "media_player.test"
    )
```

**Comment by MatthewFlamm** [comment]
Since you aren't using config flow or config entries in your integration, tests 4-5 can be removed from consideration.  I can see that your integration is using MQTT, and I honestly do not have direct experience with how that works either in Home Assistant or in the testing.  I assume you need to actually send a mqtt_message to set the state?  Something like this?

https://github.com/home-assistant/core/blob/4ed1f8023b3e369d3867f0121e8a82b8e3d55c1b/tests/components/mqtt/test_state_vacuum.py#L239

**Comment by MatthewFlamm** [comment]
I'm going to close this as I do not believe we are discussing an issue with this library.  Please reopen if you feel otherwise.  If you want to discuss how to run the tests, you can DM me on discord.
