### ISSUE TITLE
enabling sockets on 0.4.6

### ISSUE THREAD

**Issue by drc38** [MatthewFlamm/pytest-homeassistant-custom-component#96]
How do you enable sockets for testing in the latest version? I have tried adding the following to `conftest.py`:
```
from pytest_socket import enable_socket

def pytest_runtest_setup():
    """Enable socket for tests - default is to disable."""
    enable_socket()
```
and the following in the test function:
```
async def test_cms_responses(hass, socket_enabled):
```
but still get `pytest_socket.SocketConnectBlockedError:` raised when the test runs.

**Comment by MatthewFlamm** [comment]
I'm not very familiar but have you tried the built in fixture?

https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/blob/47521e5ffc41f921ec822390199307c1325c7bdd/pytest_homeassistant_custom_component/plugins.py#L96

**Comment by drc38** [comment]
> I'm not very familiar but have you tried the built in fixture?
> 
> https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/blob/47521e5ffc41f921ec822390199307c1325c7bdd/pytest_homeassistant_custom_component/plugins.py#L96

How do you use the fixture in a test function or `conftest.py`,  I tried passing `socket_enabled` to the function as per the example above but that didn't work.

**Comment by MatthewFlamm** [comment]
> How do you use the fixture in a test function or `conftest.py`, I tried passing `socket_enabled` to the function as per the example above but that didn't work.

Like you did in your original comment.  I'm not sure how the socket functionality works, but if you figure it out, we can put in a pointer here.

**Comment by MatthewFlamm** [comment]
All the examples in the core repo look something like this:

https://github.com/home-assistant/core/blob/4746ff379823fe552cb241a5fa65ebb59cdc20f3/tests/components/motioneye/test_camera.py#L66

**Comment by drc38** [comment]
I have not had any luck with resolving, this suggests it may be related to the fixture resolution order: 
https://github.com/miketheman/pytest-socket/issues/45

and a similar issue reported here:
https://github.com/miketheman/pytest-socket/issues/57

**Comment by drc38** [comment]
Does having `pytest_runtest_setup` in the plugin override or prevent `enable_socket` being set by the local test function setup?

**Comment by MatthewFlamm** [comment]
I believe that the default behavior in the plugins here is to allow only host `127.0.0.1`.  Have you verified that it isn't failing because of trying to reach another host?

**Comment by drc38** [comment]
Thanks, I managed to get it working by changing all `localhost` references explicitly to `127.0.0.1` and using the `socket_enabled` marker. In my view the plug-in code should also explicitly allow `::1` which is equivalent to `127.0.0.1` and referenced in the error message as a blocked address.

**Comment by MatthewFlamm** [comment]
> In my view the plug-in code should also explicitly allow `::1` which is equivalent to `127.0.0.1` and was referenced in the error message as a blocked address.

I'm going to close this, since it seems you have an issue with either `pytest-socket` or the implementation thereof in `home-assistant/core`.  The plugins here are taken directly from `home-assistant/core` with only minimal changes needed for custom components.  These minimal changes are mainly due to file path changes when testing directly in `core` vs. as a custom component.
