### ISSUE TITLE
Home assistant version in release information

### ISSUE THREAD

**Issue by argoyle** [MatthewFlamm/pytest-homeassistant-custom-component#98]
It would be nice to have the Home Assistant version that the release is targeting in the release information.

The Dependabot info is a bit limited when it wants to update my component:
![image](https://user-images.githubusercontent.com/328334/142139722-12461e2c-178d-4784-ab92-35f8ac95bb37.png)

**Comment by MatthewFlamm** [comment]
Going to reopen this as the slightly more manual, but still scripted, release method hasn't been updated yet.

**Comment by MatthewFlamm** [comment]
Need to add here, probably using the version in the `ha_version` file
https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/blob/66c805564cf91271f962f3c23e3b05e428ba08c3/.github/workflows/make_release.yml#L42-L43

**Comment by MatthewFlamm** [comment]
This also works now in the more manual release which was needed for 2021.12
